// CommonJS, every file is module (by default)
// Modules - Encapsulated code (only share minimum)
const names = require("./4-names")
const sayHi = require("./5-utils")
const data = require('./6-alternative-falvor')
require('./7-mind-granade')
sayHi("Humbal")
sayHi(names.Arqam)
sayHi(names.Maaz)